class Item {
  String imgPath;
  double price;
  String location;
  String name;
  String desc;


  Item({required this.imgPath, required this.name, required this.price, this.location = "Benha" , this.desc="ANY THING"});
}

final List<Item> items = [
  Item(name: "EOS 4000D DSLR", price: 500, imgPath: "assets/img/1.jpeg", location: "Benha" ,desc: "Canon is proud of its long and unwavering tradition of protecting and preserving our most precious of resources - the world we share. We work to harmonize environmental commitment and economic interests in all our business activities. We believe this balance is essential to sustain prosperity for future generations."),
  Item(name: "Wireless Controlle", price: 50, imgPath: "assets/img/2.jpeg" , location: "kafr shokr" , desc: "Discover an even more intense and engaging gaming experience1 that brings the action in your hands to life The dualsense wireless controller provides immersive haptic feedback, dynamic adaptive triggers Take control with an advanced two tone design that combines an iconic, intuitive layout with improved sticks"),
  Item(name: "Air Pods Pro", price: 100, imgPath: "assets/img/3.jpeg" , location: "Mansora" , desc: "Updated design AirPods are lightweight and offer a contoured design. They sit at just the right angle for comfort and to better direct audio to your ear. The stem is 33 per cent shorter than AirPods and includes a force sensor to easily control music and calls. Spatial Audio with dynamic head tracking Sound is placed all around you to create an immersive, three-dimensional listening experience for music"),
  Item(name: "Wireless Headphone", price: 70, imgPath: "assets/img/4.jpeg" , location: "khattab" , desc: "We've reinvented headphones and taken them to new levels. Air Max is designed to isolate the sound to the maximum in its various parts, from the ear liner to the headband, to fit all head shapes, and provide a unique listening experience The head frame distributes the weight of the headphones evenly to relieve stress on the head An amazing combination of flexibility and comfort"),
  Item(name: "Dell", price: 700, imgPath: "assets/img/5.jpeg" , desc: "Get the amazing Dell 5520-G15 Gaming Laptop With 15.6 Inch Core i7 laptop with features latest advancements delivering efficient performance. Witness the super-smooth activity with the Core Dell 5520-G15 Gaming Laptop With 15.6 Inch Core i7 laptop that takes your performance to a whole new level."),
  Item(name: "Lenovo", price: 650, imgPath: "assets/img/6.jpeg" , desc: "Get the amazing Dell 5520-G15 Gaming Laptop With 15.6 Inch Core i7 laptop with features latest advancements delivering efficient performance. Witness the super-smooth activity with the Core Dell 5520-G15 Gaming Laptop With 15.6 Inch Core i7 laptop that takes your performance to a whole new level."),
  Item(name: "Hp", price: 600, imgPath: "assets/img/7.jpeg" , desc: "Get the amazing Dell 5520-G15 Gaming Laptop With 15.6 Inch Core i7 laptop with features latest advancements delivering efficient performance. Witness the super-smooth activity with the Core Dell 5520-G15 Gaming Laptop With 15.6 Inch Core i7 laptop that takes your performance to a whole new level."),
  Item(name: "TORNADO", price: 400, imgPath: "assets/img/8.jpeg" , desc: "The 43-inch 43ER9300E is an efficient and convenient option for those who value both functionality and quality. It combines a Full HD display with the added benefit of a built-in receiver, providing access to a variety of channels. The inclusion of multiple HDMI and USB ports ensures that it can handle a range of devices, catering to all multimedia needs."),
  Item(name: "SAMSUNG", price: 500, imgPath: "assets/img/9.jpeg" , desc: "The 43-inch 43ER9300E is an efficient and convenient option for those who value both functionality and quality. It combines a Full HD display with the added benefit of a built-in receiver, providing access to a variety of channels. The inclusion of multiple HDMI and USB ports ensures that it can handle a range of devices, catering to all multimedia needs."),
  Item(name: "SAMSUNG", price: 500, imgPath: "assets/img/10.jpeg" , desc: "The 43-inch 43ER9300E is an efficient and convenient option for those who value both functionality and quality. It combines a Full HD display with the added benefit of a built-in receiver, providing access to a variety of channels. The inclusion of multiple HDMI and USB ports ensures that it can handle a range of devices, catering to all multimedia needs."),
  Item(name: "TORNADO", price: 550, imgPath: "assets/img/11.jpeg" , desc: "The 43-inch 43ER9300E is an efficient and convenient option for those who value both functionality and quality. It combines a Full HD display with the added benefit of a built-in receiver, providing access to a variety of channels. The inclusion of multiple HDMI and USB ports ensures that it can handle a range of devices, catering to all multimedia needs."),
  Item(name: "TORNADO", price: 550, imgPath: "assets/img/12.jpeg" , desc: "The 43-inch 43ER9300E is an efficient and convenient option for those who value both functionality and quality. It combines a Full HD display with the added benefit of a built-in receiver, providing access to a variety of channels. The inclusion of multiple HDMI and USB ports ensures that it can handle a range of devices, catering to all multimedia needs."),
  Item(name: "SAMSUNG", price: 700, imgPath: "assets/img/13.jpeg" , desc: "The 43-inch 43ER9300E is an efficient and convenient option for those who value both functionality and quality. It combines a Full HD display with the added benefit of a built-in receiver, providing access to a variety of channels. The inclusion of multiple HDMI and USB ports ensures that it can handle a range of devices, catering to all multimedia needs."),
  Item(name: "SAMSUNG", price: 700, imgPath: "assets/img/14.jpeg" , desc: "The 43-inch 43ER9300E is an efficient and convenient option for those who value both functionality and quality. It combines a Full HD display with the added benefit of a built-in receiver, providing access to a variety of channels. The inclusion of multiple HDMI and USB ports ensures that it can handle a range of devices, catering to all multimedia needs."),
];
